"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import quote_plus

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ===========================================
# CARGAR VARIABLES DE ENTORNO DESDE .env
# ===========================================
from dotenv import load_dotenv

load_dotenv()


# Función helper para obtener variables obligatorias
def get_required_env(var_name, description=""):
    value = os.environ.get(var_name)
    if not value:
        # Valor por defecto para desarrollo
        if var_name == "SECRET_KEY":
            return "django-insecure-dev-key-change-in-production"
        if var_name == "DEBUG":
            return "False"
        if var_name == "ALLOWED_HOSTS":
            return "*"
        # print(f"⚠️ Variable de entorno requerida: {var_name}. {description}")
        return None
    return value


# ===========================================
# MONGO DB CONFIGURATION - GUARDAR COMO ATRIBUTOS DE MÓDULO
# ===========================================
MONGO_URI = os.environ.get("MONGO_URI")
MONGO_ATLAS_SQL_URI = os.environ.get("MONGO_ATLAS_SQL_URI")

# Si no hay URI completa, construir desde componentes
if not MONGO_URI:
    # These MUST be module-level attributes for database.py to access them
    MONGO_USER = os.environ.get("MONGO_USER", "jonaaxsic")
    MONGO_PASSWORD = os.environ.get("MONGO_PASSWORD")
    MONGO_HOST = os.environ.get("MONGO_HOST", "main-database.rpaamyh.mongodb.net")
    MONGO_DB_NAME = os.environ.get("MONGO_DB_NAME", "App_estudiantil")
    MONGO_PORT = int(os.environ.get("MONGO_PORT", 27017))

    # Build Atlas URI if password exists
    if MONGO_PASSWORD:
        password = quote_plus(MONGO_PASSWORD)
        MONGO_URI = (
            f"mongodb+srv://{MONGO_USER}:{password}@{MONGO_HOST}/?appName=Main-Database"
        )
else:
    # When MONGO_URI is provided directly, extract components for compatibility
    MONGO_USER = os.environ.get("MONGO_USER", "")
    MONGO_PASSWORD = os.environ.get("MONGO_PASSWORD", "")
    MONGO_HOST = os.environ.get("MONGO_HOST", "main-database.rpaamyh.mongodb.net")
    MONGO_DB_NAME = os.environ.get("MONGO_DB_NAME", "App_estudiantil")
    MONGO_PORT = int(os.environ.get("MONGO_PORT", 27017))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY", "django-insecure-dev-key-change-in-production"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False") == "True"

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "*").split(",")


# Application definition

INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "core",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.common.CommonMiddleware",
]

ROOT_URLCONF = "urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "wsgi.application"

# Database - Using SQLite for local development
# (MongoDB Atlas connection is not available in this environment)
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "es-cl"

TIME_ZONE = "America/Santiago"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# REST Framework settings
REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
    ],
}
